version: '3'

services:
    web:
        image: staticfloat/nginx-certbot
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - ${CODE_DIR}:/code
            - ./conf.d:/etc/nginx/user.conf.d:ro
            - ./certbot_extra_domains:/etc/nginx/certbot/extra_domains:ro
        environment:
            CERTBOT_EMAIL: ${CERTBOT_EMAIL}
        networks:
            - code-network
    php:
        build: ./php
        volumes:
            - ${CODE_DIR}:/code
        networks:
            - code-network

networks:
    code-network:
        driver: bridge
